services:
  app:
    build: .
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
